# Generated by Django 5.1.3 on 2025-02-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_contactrequest_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='member',
            name='twitter',
        ),
        migrations.AddField(
            model_name='member',
            name='github',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
