# Generated by Django 5.1.3 on 2025-03-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_event_image_alter_notice_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notice', 'verbose_name_plural': 'Notices'},
        ),
    ]
